### PR TITLE
fix: Check hideshowvis-ignore-same-line before making overlay.

### LINKED ISSUE #11: Leak in overlays when hideshowvis-ignore-same-line is t
# Bug

In this code:

https://github.com/sheijk/hideshowvis/blob/e48500ef9f569d597b87be172a6dbe32ad8876a8/hideshowvis.el#L143-L158

We see that an overlay is created on line 143.  On lines 146-158, if `hideshowvis-ignore-same-line` is `t` then we might not actually use the overlay just created, by setting `doit` to false.

When we don't use the overlay, we also don't later on set the property `hideshowvis-hs` on the overlay, which is done on line 168 within the `when doit` block.

This causes the code to sometimes create overlays without putting the `hideshowvis-hs` property on them.

---

When recomputing the overlays, the first step is to remove all the old overlays, on this line: https://github.com/sheijk/hideshowvis/blob/e48500ef9f569d597b87be172a6dbe32ad8876a8/hideshowvis.el#L141

However, it only removes the overlays with the `hideshowvis-hs` property.  The overlays for which `doit` was not true will never get deleted, and this causes the number of overlays to balloon, leading to major slowdowns in the buffer.

# Testing

1. Open a buffer with hideshowvis enabled and type `M-: (length (overlay-lists))`.  You will see how many overlays there are. 
2. `M-x revert-buffer` to reload the buffer.  This will recompute the hideshowvis.
3. Again `M-: (length (overlay-lists))`.  You will see that there are many more overlays now.

If you do this test with `hideshowvis-ignore-same-line` set to `t` then it will not balloon the number of overlays because they will all get marked with the `hideshowvis-hs` property.

# Solution

Very simple: In the case of doit false, don't make an overlay in the first place!

### PR DESCRIPTION
**Pull request by eyal0**
This fixes #11.

### CODE REVIEW

**Comment by eyal0** [comment]
This also greatly improves performance in my testing.  Do many `revert-buffer` in a row and see how performance is maintained.

**Comment by Hi-Angel** [comment]
Just a small note: if you want the issue to get closed when the PR is merged, the syntax is:

```
Fixes: https://github.com/sheijk/hideshowvis/issues/11
```

Alternatively `Closes` keyword may be used. I don't think `This fixes …` as a line will work in this case.

**Comment by eyal0** [comment]
@Hi-Angel in my experience, the syntax that I used will work, too. In fact, on my phone, I can see a faint underline under the words "fixes" because GitHub has picked up this meaning.

Also, on the right side of the screen here, I see a note indicating that merging this PR may close the issue. (It says "may" because the owner, when merging this, can elect not to close the issue.)

Screenshot_20240527_162016_Firefox

I feel very confident that the syntax I used will work.

**Comment by sheijk** [comment]
@eyal0 good catch, thanks for the fix!

**Comment by sheijk** [comment]
@eyal0 I'd also add you to the [contributors list](https://github.com/sheijk/hideshowvis/blob/7b174241c9381afb0d55c8bdc52b727323ce76bc/hideshowvis.el#L10). If you want to just let me know what name I should put

**Comment by eyal0** [comment]
Took me embarrassingly long to figure out! My coding files reload a bunch due to git commands causing me to need to `revert-buffer` frequently and each one made a bunch of new overlays. I never noticed it in the profiler because those overlays are processed in c++ and not elisp, I think.

I did a bisect of my init file, commenting out lines, looking for a suspect. I then scanned through this code and, on a hunch, tried `overlays-list`. That got me the answer.

I am Eyal Soha.

**Pull request merged**
